names:
  - 1
  - 8

# Specify how the data needs to be sliced before feeding to the network.
# We use a 3D sliding window over the dataset to extract patches, which
# are then fed to the network as batches.
slicing_config:
  # Sliding window size
  window_size:
    [32, 276, 276]
  # Sliding window stride
  stride:
    [4, 32, 32]

defect_augmentation_config:
    p_missing_slice: 0.01
    p_low_contrast: 0.01
    p_deformed_slice: 0.01
    p_artifact_source: 0.01
    deformation_mode: 'undirected'
    deformation_strength: 16
    artifact_source:
        min_masking_ratio: .5
        slicing_config:
          window_size: [1, 276, 276]
          stride: [1, 32, 32]
        volume_config:
          artifacts:
            path: '/g/kreshuk/pape/Work/data/rompani/neuron_training_data/defects.h5'
            path_in_h5_dataset: 'defect_sections/raw'
            dtype: float32
          alpha_mask:
            path: '/g/kreshuk/pape/Work/data/rompani/neuron_training_data/defects.h5'
            path_in_h5_dataset: 'defect_sections/mask'
        master_config:
          elastic_transform:
            alpha: 2000.
            sigma: 50.
    
# Specify paths to volumes
volume_config:
  # Raw data
  raw:
    path:
      1: '/g/kreshuk/pape/Work/data/rompani/neuron_training_data/v1/block_1.h5'
      8: '/g/kreshuk/pape/Work/data/rompani/neuron_training_data/v1/block_8.h5'
    path_in_file:
      1: 'raw'
      8: 'raw'
    dtype: float32
    sigma: 0.025
  # Segmentation
  segmentation:
    path:
      1: '/g/kreshuk/pape/Work/data/rompani/neuron_training_data/v1/block_1.h5'
      8: '/g/kreshuk/pape/Work/data/rompani/neuron_training_data/v1/block_8.h5'
    path_in_file:
      1: 'labels'
      8: 'labels'
    dtype: int64
  rejection_threshold: 0.1


# TODO implement slides along all axis to simulate defects ?!
# to mimic stitching artifacts
# Configuration for the master dataset.
master_config:
  # We might need order 0 interpolation if we have segmentation in there somewhere.
  elastic_transform:
    alpha: 2000.
    sigma: 50.
    order: 0
  random_slides: True
  shape_after_slide: [256, 256]


# Specify configuration for the loader
loader_config:
  # Number of processes to use for loading data. Set to (say) 10 if you wish to
  # use 10 CPU cores, or to 0 if you wish to use the same process for training and
  # data-loading (generally not recommended).
  batch_size: 1
  num_workers: 6
  drop_last: True
  pin_memory: False
  shuffle: True
