# The model arguments
model_name: AnisotropicUNet
model_kwargs:
  in_channels: 1
  out_channels: 6
  initial_features: 32
  gain: 2
  scale_factors: [[1, 2, 2], [1, 2, 2], 2, 2]
  final_activation: Sigmoid
  pad_convs: True
  norm: GroupNorm

training_optimizer_kwargs:
  method: Adam
  lr: 0.001
  weight_decay: 0.0005

devices:
  - 0
