defect_augmentation_config:
  deformation_mode: undirected
  deformation_strength: 16
  p_artifact_source: 0.0
  p_deformed_slice: 0.0
  p_low_contrast: 0.01
  p_missing_slice: 0.0
loader_config:
  batch_size: 1
  drop_last: true
  num_workers: 6
  pin_memory: false
  shuffle: true
master_config:
  elastic_transform:
    alpha: 1000.0
    order: 0
    sigma: 50.0
  random_slides: false
  shape_after_slide:
  - 160
  - 160
names:
- 974
- 976
- 977
- 978
- 979
- 98
- 980
- 981
- 982
- 983
- 984
- 985
- 986
- 987
- 988
- 989
- 99
- 990
- 991
- 992
- 993
- 994
- 995
- 996
- 997
- 998
- 999
slicing_config:
  stride:
  - 4
  - 40
  - 40
  window_size:
  - 32
  - 160
  - 160
volume_config:
  raw:
    dtype: float32
    path:
      1: /g/rompani/pape/lgn/tranining_data/boutons/V3/bdv/training_data_01.h5
      98: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/98.h5
      99: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/99.h5
      974: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/974.h5
      976: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/976.h5
      977: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/977.h5
      978: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/978.h5
      979: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/979.h5
      980: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/980.h5
      981: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/981.h5
      982: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/982.h5
      983: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/983.h5
      984: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/984.h5
      985: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/985.h5
      986: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/986.h5
      987: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/987.h5
      988: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/988.h5
      989: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/989.h5
      990: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/990.h5
      991: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/991.h5
      992: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/992.h5
      993: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/993.h5
      994: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/994.h5
      995: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/995.h5
      996: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/996.h5
      997: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/997.h5
      998: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/998.h5
      999: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/999.h5
    path_in_file:
      1: raw
      98: raw
      99: raw
      974: raw
      976: raw
      977: raw
      978: raw
      979: raw
      980: raw
      981: raw
      982: raw
      983: raw
      984: raw
      985: raw
      986: raw
      987: raw
      988: raw
      989: raw
      990: raw
      991: raw
      992: raw
      993: raw
      994: raw
      995: raw
      996: raw
      997: raw
      998: raw
      999: raw
    sigma: 0.025
  rejection_threshold: 0.1
  segmentation:
    dtype: int64
    path:
      1: /g/rompani/pape/lgn/tranining_data/boutons/V3/bdv/training_data_01.h5
      98: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/98.h5
      99: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/99.h5
      974: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/974.h5
      976: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/976.h5
      977: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/977.h5
      978: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/978.h5
      979: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/979.h5
      980: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/980.h5
      981: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/981.h5
      982: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/982.h5
      983: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/983.h5
      984: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/984.h5
      985: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/985.h5
      986: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/986.h5
      987: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/987.h5
      988: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/988.h5
      989: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/989.h5
      990: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/990.h5
      991: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/991.h5
      992: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/992.h5
      993: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/993.h5
      994: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/994.h5
      995: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/995.h5
      996: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/996.h5
      997: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/997.h5
      998: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/998.h5
      999: /g/kreshuk/data/helmstaedter/training_data/neurons/rompani/999.h5
    path_in_file:
      1: labels
      98: labels_postprocessed/restricted
      99: labels_postprocessed/restricted
      974: labels_postprocessed/restricted
      976: labels_postprocessed/restricted
      977: labels_postprocessed/restricted
      978: labels_postprocessed/restricted
      979: labels_postprocessed/restricted
      980: labels_postprocessed/restricted
      981: labels_postprocessed/restricted
      982: labels_postprocessed/restricted
      983: labels_postprocessed/restricted
      984: labels_postprocessed/restricted
      985: labels_postprocessed/restricted
      986: labels_postprocessed/restricted
      987: labels_postprocessed/restricted
      988: labels_postprocessed/restricted
      989: labels_postprocessed/restricted
      990: labels_postprocessed/restricted
      991: labels_postprocessed/restricted
      992: labels_postprocessed/restricted
      993: labels_postprocessed/restricted
      994: labels_postprocessed/restricted
      995: labels_postprocessed/restricted
      996: labels_postprocessed/restricted
      997: labels_postprocessed/restricted
      998: labels_postprocessed/restricted
      999: labels_postprocessed/restricted
